/*
 * H3Lite Region Lookup Table
 * Generated by generate_lookup_table.py
 */

#ifndef H3LITE_REGIONS_TABLE_H
#define H3LITE_REGIONS_TABLE_H

#include <stdint.h>
#include "h3lite.h"

// Region IDs
#define REGION_US915 1
#define REGION_EU868 2
#define REGION_AU915 3
#define REGION_AS923_1 4
#define REGION_AS923_2 5
#define REGION_AS923_3 6
#define REGION_AS923_4 7
#define REGION_KR920 8
#define REGION_IN865 9
#define REGION_RU864 10
#define REGION_CN470 11
#define REGION_EU433 12

// Number of entries in the lookup table
#define REGION_ENTRY_COUNT 10875

// Lookup entry structure
typedef struct {
    uint8_t baseCell;      // Base cell (0-121)
    uint16_t partialIndex; // Partial index for first few resolutions
    RegionId regionId;     // Region ID (1-12)
} RegionEntry;

// Region lookup table (sorted by baseCell and partialIndex)
extern const RegionEntry regionLookup[REGION_ENTRY_COUNT];

// Region names array
extern const char* regionNames[13];

// Binary search the region lookup table
RegionId findRegion(uint8_t baseCell, uint16_t partialIndex);

#endif /* H3LITE_REGIONS_TABLE_H */
