/*
 * H3Lite Region Lookup Table
 * Generated by generate_lookup_table.py
 */

#ifndef H3LITE_REGIONS_TABLE_H
#define H3LITE_REGIONS_TABLE_H

#include <stdint.h>
#include "h3lite.h"

// Region IDs
#define REGION_US915 1
#define REGION_EU868 2
#define REGION_AU915 3
#define REGION_AS923_1 4
#define REGION_AS923_1B 5
#define REGION_AS923_1C 6
#define REGION_AS923_2 7
#define REGION_AS923_3 8
#define REGION_AS923_4 9
#define REGION_KR920 10
#define REGION_IN865 11
#define REGION_RU864 12
#define REGION_CN470 13
#define REGION_EU433 14
#define REGION_CD900_1A 15

// Number of entries in the lookup table
#define REGION_ENTRY_COUNT 4556

/* Packed entry (H3-1/H3-4):
 *   bits [31:25] baseCell (0-121)
 *   bits [24:23] resolution (1-3)
 *   bits [22:14] partialIndex (0-511)
 *   bits [13:10] regionId (0-15)
 *   bits [9:0]   reserved (zero)
 * Sorted ascending by (baseCell, resolution, partialIndex) — which is
 * numeric order of the packed value. */
typedef uint32_t RegionEntry;

#define RE_BASECELL(e)  ((uint8_t)(((e) >> 25) & 0x7F))
#define RE_RES(e)       ((uint8_t)(((e) >> 23) & 0x03))
#define RE_PARTIAL(e)   ((uint16_t)(((e) >> 14) & 0x1FF))
#define RE_REGION(e)    ((RegionId)(((e) >> 10) & 0x0F))

// Region lookup table (sorted by baseCell, resolution, partialIndex)
extern const RegionEntry regionLookup[REGION_ENTRY_COUNT];

// Region names array
extern const char* regionNames[16];

// Binary search the region lookup table for an exact
// (baseCell, resolution, partialIndex) key; returns 0 (Unknown) on miss.
RegionId findRegion(uint8_t baseCell, uint8_t res, uint16_t partialIndex);

#endif /* H3LITE_REGIONS_TABLE_H */
